/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './resources/views/**/*.blade.php',
    './resources/js/**/*.jsx',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#1c1b1b',
        'surface-tint': '#b62413',
        'surface-container-high': '#ffe2dd',
        'secondary': '#5f5e5e',
        'inverse-primary': '#ffb4a7',
        'secondary-container': '#e5e2e1',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        'inverse-on-surface': '#ffedea',
        'outline': '#8f706a',
        'surface-container-low': '#fff0ee',
        'secondary-fixed': '#e5e2e1',
        'on-surface-variant': '#5b403c',
        'surface-dim': '#f0d4cf',
        'on-secondary-container': '#656464',
        'tertiary': '#006579',
        'on-secondary': '#ffffff',
        'surface-variant': '#f9dcd7',
        'on-tertiary-fixed-variant': '#004e5e',
        'on-error-container': '#93000a',
        'secondary-fixed-dim': '#c8c6c5',
        'on-primary-fixed-variant': '#910900',
        'surface-container-lowest': '#ffffff',
        'on-background': '#271815',
        'inverse-surface': '#3d2c29',
        'outline-variant': '#e3beb8',
        'surface-container': '#ffe9e5',
        'tertiary-fixed': '#b2ebff',
        'on-error': '#ffffff',
        'on-surface': '#271815',
        'surface-bright': '#fff8f6',
        'on-primary-container': '#fffbff',
        'surface': '#fff8f6',
        'error': '#ba1a1a',
        'on-secondary-fixed-variant': '#474646',
        'error-container': '#ffdad6',
        'surface-container-highest': '#f9dcd7',
        'on-primary-fixed': '#400200',
        'primary': '#b22110',
        'primary-container': '#d63b27',
        'on-tertiary-container': '#f9fdff',
        'primary-fixed': '#ffdad4',
        'tertiary-fixed-dim': '#68d4f3',
        'on-tertiary-fixed': '#001f27',
        'tertiary-container': '#007f99',
        'background': '#fff8f6',
        'primary-fixed-dim': '#ffb4a7'
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'card-padding': '0.75rem',
        'gap-tight': '1rem',
        'gap-default': '1.25rem',
        'container-padding': '1.5rem',
      },
      fontFamily: {
        'body-md': ['Inter'],
        'label-md': ['Inter'],
        'headline-lg': ['Inter'],
        'body-lg': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'headline-md': ['Inter'],
        'caption': ['Inter'],
        'headline-sm': ['Inter'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '1', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['15px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'caption': ['11px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '400' }],
        'headline-sm': ['16px', { lineHeight: '1.4', fontWeight: '600' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
