/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#ffedea",
        "on-tertiary-fixed-variant": "#004e5e",
        "on-primary-fixed-variant": "#910900",
        "on-secondary-fixed-variant": "#474646",
        "on-secondary-fixed": "#1c1b1b",
        "on-surface": "#271815",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container": "#ffe9e5",
        "surface-container-highest": "#f9dcd7",
        "inverse-surface": "#3d2c29",
        "surface-container-low": "#fff0ee",
        "on-background": "#271815",
        "secondary": "#5f5e5e",
        "tertiary-fixed-dim": "#68d4f3",
        "tertiary-container": "#007f99",
        "primary-container": "#d63b27",
        "surface-bright": "#fff8f6",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#fffbff",
        "on-surface-variant": "#5b403c",
        "on-tertiary-fixed": "#001f27",
        "outline": "#8f706a",
        "surface-container-high": "#ffe2dd",
        "surface-dim": "#f0d4cf",
        "primary-fixed-dim": "#ffb4a7",
        "primary-fixed": "#ffdad4",
        "on-primary-fixed": "#400200",
        "secondary-container": "#e5e2e1",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-tint": "#b62413",
        "secondary-fixed-dim": "#c8c6c5",
        "primary": "#b22110",
        "background": "#fff8f6",
        "on-error": "#ffffff",
        "surface": "#fff8f6",
        "on-tertiary-container": "#f9fdff",
        "inverse-primary": "#ffb4a7",
        "on-secondary": "#ffffff",
        "surface-variant": "#f9dcd7",
        "tertiary": "#006579",
        "on-secondary-container": "#656464",
        "tertiary-fixed": "#b2ebff",
        "outline-variant": "#e3beb8",
        "secondary-fixed": "#e5e2e1",
        "coral-red": "#F04E37",
        "coral-light": "#FFF0EE",
        "coral-dark": "#B83020",
        "divider": "#EBEBEB",
        "surface-f5": "#F5F5F7",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-padding": "1.5rem",
        "gap-tight": "1rem",
        "gap-default": "1.25rem",
        "card-padding": "0.75rem",
        "stack-lg": "32px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "gutter": "24px",
        "sidebar-width": "240px",
        "content-max-width": "1200px"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        "caption": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "label-md": ["Inter"],
        "headline-sm": ["Inter"]
      },
      fontSize: {
        "caption": ["11px", {"lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "500"}],
        "headline-md": ["20px", {"lineHeight": "1.4", "fontWeight": "500"}],
        "body-md": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "body-lg": ["15px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "1.2", "fontWeight": "500"}],
        "label-md": ["12px", {"lineHeight": "1.1", "fontWeight": "500"}],
        "headline-sm": ["16px", {"lineHeight": "1.4", "fontWeight": "500"}],
        "headline-xl": ["28px", {"lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "500"}],
        "label-sm": ["11px", {"lineHeight": "14px", "fontWeight": "500"}]
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'hero-pattern': 'linear-gradient(135deg, #1e1b4b 0%, #312e81 50%, #4c1d95 100%)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'float': 'float 3s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
    },
  },
  plugins: [],
}
